#!/usr/bin/env python3
"""Generate ASCII Rust Unicode 16.0 general-category tables from UCD."""
import re
import sys

GC = {
    "Lu": 1, "Ll": 2, "Lt": 3, "Lm": 4, "Lo": 5,
    "Mn": 6, "Mc": 7, "Me": 8,
    "Nd": 9, "Nl": 10, "No": 11,
    "Pc": 12, "Pd": 13, "Ps": 14, "Pe": 15, "Pi": 16, "Pf": 17, "Po": 18,
    "Sm": 19, "Sc": 20, "Sk": 21, "So": 22,
    "Zs": 23, "Zl": 24, "Zp": 25,
    "Cc": 26, "Cf": 27, "Cs": 28, "Co": 29,
    # Cn is default (0)
}

def main():
    src = sys.argv[1]
    dst = sys.argv[2]
    ranges = []
    pat = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Z][a-z])")
    with open(src, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = pat.match(line)
            if not m:
                continue
            a = int(m.group(1), 16)
            b = int(m.group(2) or m.group(1), 16)
            g = m.group(3)
            if g == "Cn":
                continue
            gid = GC.get(g)
            if gid is None:
                continue
            ranges.append((a, b, gid, g))
    ranges.sort()
    merged = []
    for a, b, gid, g in ranges:
        if merged and merged[-1][2] == gid and merged[-1][1] + 1 == a:
            merged[-1] = (merged[-1][0], b, gid, g)
        else:
            merged.append((a, b, gid, g))
    out = []
    out.append("//! Unicode 16.0 general-category ranges (UCD DerivedGeneralCategory).")
    out.append("//! Generated by tools/gen_ucd16.py. Do not edit by hand.")
    out.append("")
    out.append("#![allow(dead_code)]")
    out.append("")
    out.append("pub const GC_LU: u8 = 1;")
    out.append("pub const GC_CN: u8 = 0;")
    out.append("")
    out.append("pub static GC_RANGES: &[(u32, u32, u8)] = &[")
    for a, b, gid, _g in merged:
        out.append(f"    (0x{a:04x}, 0x{b:04x}, {gid}),")
    out.append("];")
    out.append("")
    out.append("pub fn gc(cp: u32) -> u8 {")
    out.append("    let t = GC_RANGES;")
    out.append("    let mut lo = 0usize;")
    out.append("    let mut hi = t.len();")
    out.append("    while lo < hi {")
    out.append("        let mid = (lo + hi) / 2;")
    out.append("        let (a, b, g) = t[mid];")
    out.append("        if cp < a {")
    out.append("            hi = mid;")
    out.append("        } else if cp > b {")
    out.append("            lo = mid + 1;")
    out.append("        } else {")
    out.append("            return g;")
    out.append("        }")
    out.append("    }")
    out.append("    0")
    out.append("}")
    out.append("")
    out.append("pub fn gc_name(g: u8) -> &'static str {")
    out.append("    match g {")
    names = [
        (1, "Lu"), (2, "Ll"), (3, "Lt"), (4, "Lm"), (5, "Lo"),
        (6, "Mn"), (7, "Mc"), (8, "Me"),
        (9, "Nd"), (10, "Nl"), (11, "No"),
        (12, "Pc"), (13, "Pd"), (14, "Ps"), (15, "Pe"), (16, "Pi"), (17, "Pf"), (18, "Po"),
        (19, "Sm"), (20, "Sc"), (21, "Sk"), (22, "So"),
        (23, "Zs"), (24, "Zl"), (25, "Zp"),
        (26, "Cc"), (27, "Cf"), (28, "Cs"), (29, "Co"),
        (0, "Cn"),
    ]
    for i, n in names:
        out.append(f'        {i} => "{n}",')
    out.append('        _ => "Cn",')
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("pub fn gc_eq(cp: u32, name: &str) -> bool {")
    out.append("    let g = gc(cp);")
    out.append("    if name.len() == 1 {")
    out.append("        return gc_name(g).as_bytes().first().copied() == name.as_bytes().first().copied();")
    out.append("    }")
    out.append("    gc_name(g) == name")
    out.append("}")
    out.append("")
    with open(dst, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(out))
        f.write("\n")
    print(f"wrote {len(merged)} ranges to {dst}")

if __name__ == "__main__":
    main()
